// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/public/contact': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/public/contact.post').default>>>>
    }
    '/api/public/content-list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/public/content-list.get').default>>>>
    }
    '/api/public/content': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/public/content.get').default>>>>
    }
    '/api/public/events': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/public/events.post').default>>>>
    }
    '/api/public/page': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/public/page.get').default>>>>
    }
    '/api/public/resolve': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/public/resolve.get').default>>>>
    }
    '/api/public/routes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/public/routes.get').default>>>>
    }
    '/api/public/site': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/public/site.get').default>>>>
    }
    '/api/public/template': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/public/template.get').default>>>>
    }
    '/robots.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/robots.txt').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/sitemap.xml').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}